# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # This ensures we don't accidentally stop supporting our lowest supported Node version (8.3)
        node-version: [16, 18, latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm ci

    - run: npm run lint

    - run: npm test

    # main doesn't have a PR for comments so skip that branch
    # We don't want 4 comments about code coverage, just just run it once on 8.3.0
    - if: ${{ github.ref != 'refs/heads/main' && matrix.node-version == 'latest' }}
      uses: romeovs/lcov-reporter-action@v0.2.21
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
